---
- name: Add Kibana apt-key
  become: yes
  apt_key: 
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
- name: Add Kibana Repository
  become: yes
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main 
    state: present
- name: Install Kibana
  become: yes
  apt:
    name: kibana
    update_cache: yes
    state: present
- name: Copy Template
  become: yes
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: 
    - Start Kibana

- name: Configure Reverse Proxy
  include: proxy.yml 
  when: user_name is defined
